# Generated by Django 4.2.6 on 2023-12-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profession', models.CharField(choices=[('DOSENT', 'Dosent'), ('LABORANT', 'Laborant'), ('PROFESSOR', 'Professor')], default='LABORANT', max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('teacher_id', models.ManyToManyField(related_name='subjectlists', to='app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smestr_type', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second')], default='FIRST', max_length=50)),
                ('course_type', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second')], default='FIRST', max_length=50)),
                ('exercise_teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_subject', to='app.teacher')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.group')),
                ('lecture_teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_subject', to='app.teacher')),
                ('subject_list_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='app.subjectlist')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('position', models.CharField(choices=[('RECTOR', 'Rector'), ('PRARECTOR', 'Prorector'), ('DEKAN', 'Dekan')], default='DEKAN', max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='app.group')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('point_type', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration', models.CharField(choices=[('SECOND', 'Second'), ('FOURTH', 'Fourth')], default='FOURTH', max_length=50)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='app.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='specaialty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.specialty'),
        ),
    ]
